name: Valinor Measurement Framework
description: >
    The page will soon host the artifacts for Valinor Project. Check out our paper from this link.
about: >
    At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.

master_repo: false
url: "https://hopnets.github.io"
markdown: kramdown
highlighter: rouge

plugins: ['jekyll-paginate', 'jekyll-gist', 'jekyll-feed']

paginate: 4

logo:             logo.png
disqus_shortname:

rtl: false
owner:
  name:           Valinor project
  avatar:         "https://avatars.githubusercontent.com/u/3146197?s=400&u=51ad0fc8f592ca960213b653ca3b01d582db44b2&v=4"
  email:          "erfan@cs.jhu.edu"
  # # Social networking links used in footer. Update and remove as you like.
  # twitter: vinitkme
  # github: https://github.com/vinitkumar
  # stackexchange: https://stackoverflow.com/users/859112/vinit-kumar?tab=profile
  # linkedin: https://www.linkedin.com/in/vinitatlinkedin
  # # For Google Authorship https://plus.google.com/authorship
  # google_plus:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:
